# Generated by Django 4.2.10 on 2024-08-02 08:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rpa", "0002_adminusers"),
    ]

    operations = [
        migrations.CreateModel(
            name="Edithistory",
            fields=[
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("edit_timestamp", models.DateTimeField()),
                ("edited_by", models.CharField(max_length=255)),
                ("field_name", models.CharField(max_length=255)),
                ("old_value", models.TextField(blank=True, null=True)),
                ("new_value", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "edithistory",
                "managed": False,
            },
        ),
    ]
