# Generated by Django 4.2.10 on 2024-08-02 08:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rpa", "0003_edithistory"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="adminusers",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="users",
            options={"managed": True},
        ),
    ]
