# Generated by Django 5.0.3 on 2024-08-06 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rpa", "0004_alter_adminusers_options_alter_users_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adminusers",
            name="passkey",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="users",
            name="email_id",
            field=models.CharField(blank=True, max_length=35, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="users",
            name="passkey",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
