INSERT INTO users VALUES ('TrfKTFIAAAAJ', 'Shahina A', 'shahinaa@ssn.edu.in', 'Welcome123');
INSERT INTO users VALUES ('tYfNLbIAAAAJ', 'Aravindan Chandrabose', 'aravindanc@ssn.edu.in', 'Welcome123');
INSERT INTO users VALUES ('xSmx77cAAAAJ', 'Srinivasan Raj', 'srinivasanr@ssn.edu.in', 'Welcome123');
INSERT INTO users VALUES ('GzCwkOgAAAAJ', 'Sivamurugan V', 'sivamuruganv@ssn.edu.in', 'Welcome123');
INSERT INTO users VALUES ('EGT63O4AAAAJ', 'Bhalaji N', 'bhalajin@ssn.edu.in', 'Welcome123');
INSERT INTO users VALUES ('40_kOTQAAAAJ', 'Karthika S', 'skarthika@ssn.edu.in', 'Welcome123');
INSERT INTO users VALUES ('p_yeFC4AAAAJ', 'Mohanavalli S', 'mohanas@ssn.edu.in', 'Welcome123');
INSERT INTO users VALUES ('C_QEcecAAAAJ', 'Vasuki P', 'vasukip@ssn.edu.in', 'Welcome123');
INSERT INTO users VALUES ('Lie21J0AAAAJ', 'Sripriya N', 'sripriyan@ssn.edu.in', 'Welcome123');
INSERT INTO users VALUES ('0oFMqd0AAAAJ', 'Uthayan K R', 'uthayankr@ssn.edu.in', 'Welcome123');
INSERT INTO users VALUES ('FG52RXYAAAAJ', 'Joe Louis Paul I', 'joelouisi@ssn.edu.in', 'Welcome123');
INSERT INTO users VALUES ('gIqdlE4AAAAJ', 'Thanikachalam V', 'thanikachalamv@ssn.edu.in', 'Welcome123');
INSERT INTO users VALUES ('Ahx_vxMAAAAJ', 'Sasirekha S', 'sasirekhas@ssn.edu.in', 'Welcome123');
INSERT INTO users VALUES ('kLRLcX8AAAAJ', 'Malathy E M', 'malathyem@ssn.edu.in', 'Welcome123');
INSERT INTO users VALUES ('MxoJelkAAAAJ', 'Radha N', 'radhan@ssn.edu.in', 'Welcome123');
INSERT INTO users VALUES ('R1odoAwAAAAJ', 'Gayathri K S', 'gayathriks@ssn.edu.in', 'Welcome123');
INSERT INTO users VALUES ('ETtcUuQAAAAJ', 'Swathika R', 'swathikar@ssn.edu.in', 'Welcome123');
INSERT INTO users VALUES ('Pio6_uAAAAAJ', 'Sandana Karuppan A', 'sandanakaruppana@ssn.edu.in', 'Welcome123');
INSERT INTO users VALUES ('8RBOaKgAAAAJ', 'Arulkumar A', 'arulkumarv@ssn.edu.in', 'Welcome123');
INSERT INTO users VALUES ('oALELhwAAAAJ', 'Sofia Jennifer J', 'sofiajenniferj@ssn.edu.in', 'Welcome123');
INSERT INTO users VALUES ('ghiPDesAAAAJ', 'Uma Maheswari S', 'umamaheswaris@ssn.edu.in', 'Welcome123');
INSERT INTO users VALUES ('tmr1MvAAAAAJ', 'Senthil Kumar B', 'senthil@ssn.edu.in', 'Welcome123');
INSERT INTO users VALUES ('YSWR6gYAAAAJ', 'Kulandai Josephine Julina J', 'josephinejulinajk@ssn.edu.in', 'Welcome123');
INSERT INTO users VALUES ('xY8YikEAAAAJ', 'Ashwinth Janarthanan', 'ashwinthj@ssn.edu.in', 'Welcome123');
INSERT INTO users VALUES ('tkfHeeAAAAAJ', 'Durgadevi Velusamy', 'durgadeviv@ssn.edu.in', 'Welcome123');
INSERT INTO users VALUES ('jXtbk7oAAAAJ', 'Saravanan A', 'saravanana@ssn.edu.in', 'Welcome123');
INSERT INTO users VALUES ('Y8DwpSIAAAAJ', 'Suganya Elavarasan', 'suganyae@ssn.edu.in', 'Welcome123');
INSERT INTO users VALUES ('v7YMzngAAAAJ', 'Sornavalli G', 'sornavallig@ssn.edu.in', 'Welcome123');
COMMIT;